// <auto-generated />
namespace ShepherdsLittleHelper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PulledFromSprint2kurtvalerie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PulledFromSprint2kurtvalerie));
        
        string IMigrationMetadata.Id
        {
            get { return "201611111549218_PulledFromSprint2kurtvalerie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
