// <auto-generated />
namespace ShepherdsLittleHelper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PulledFromStableForTesting1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PulledFromStableForTesting1));
        
        string IMigrationMetadata.Id
        {
            get { return "201611281508056_PulledFromStableForTesting1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
